version: '3.4'

services:
  darklibrary:
    image: ${DOCKER_REGISTRY-}darklibrary
    build:
      context: .
      dockerfile: DarkLibrary/Dockerfile
    environment:
      - author_api=http://localhost:6601
    ports:
      - "80:8081"
    volumes:
      - ./db/main/:/app/db/

  authorapi:
    image: ${DOCKER_REGISTRY-}authorapi
    build:
      context: .
      dockerfile: AuthorApi/Dockerfile 
    ports:
      - "6601:8081"
    volumes:
      - ./db/authors/:/app/db/

