version: '3.4'

services:
  darklibrary:
    image: ${DOCKER_REGISTRY-}darklibrary
    container_name: DarkLibrary
    build:
      context: .
      dockerfile: DarkLibrary/Dockerfile
    # ports:
    #   - "80:8081"
    depends_on:
        - sqlserver
        - authorapi
        - bookseries_api

  authorapi:
    image: ${DOCKER_REGISTRY-}authorapi
    container_name: author_api
    environment:
      - ConnectionString=Server=sqlserver;Database=author_db;User Id=sa;Password=123456789qQ;Encrypt=False;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: AuthorApi/Dockerfile 
    ports:
      - "6601:8081"
    depends_on:
        - sqlserver

  bookseriesapi:
    image: ${DOCKER_REGISTRY-}bookseriesapi
    container_name: bookseries_api
    environment:
      - ConnectionString=Server=sqlserver;Database=bookseries_db;User Id=sa;Password=123456789qQ;Encrypt=False;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: BookSeriesApi/Dockerfile
    ports:
      - "6601:8081"
    depends_on:
        - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=123456789qQ
      - ACCEPT_EULA=Y
    ports:
      - "5533:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:


